### ISSUE TITLE
CancerDB or cancerdb?

### ISSUE THREAD

**Issue by breck7** [breck7/CancerDB#10]
PLDB obviously works but CANCERDB does not. cancerDB doesn't feel right—should we just go all lowercase?

I'm voting all lowercase, unless anyone else has other opinions.

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

To be honest, for whatever reason, I've always liked the "CancerDB" version. It emphasises both aspects: (1) It's all about cancer (2) It's a database. Somehow the database part disappears if it is all in lowercase.

It is not quite camelCase, but it is an effective way of separating the two parts of the name.

Kind Regards,
Liam

**Comment by adriantintpilver** [comment]
I share that idea, I like "CancerDB"

**Comment by breck7** [comment]
Ok let's keep it as CancerDB then. Thanks everyone!
