### ISSUE TITLE
Bug with youtube videos

### ISSUE THREAD

**Issue by breck7** [breck7/CancerDB#16]
Do we need to hardcode the height and width into the HTML tag in the YouTube embeds?

https://cancerdb.com/posts/index.html

<img width="1390" alt="Screen Shot 2022-12-10 at 1 15 24 PM" src="https://user-images.githubusercontent.com/74692/206878993-aa212730-3372-426d-b2f0-b8083872469b.png">

**Comment by ege-del** [comment]
iframe with width="100%" kinda works... 
Dynamic height needs nested html elements but, I couldn't figure out how to do it in scroll.

**Comment by rkimera94** [comment]
@breck7  also on my local instance am getting this after pulling updates from the main branch.
Then ran:  npm run build

GitHub Icon 
<img width="1229" alt="Screenshot 2022-12-14 at 11 42 36" src="https://user-images.githubusercontent.com/54355787/207548012-736d206f-e9e5-4fc8-ab32-5efc0e95e629.png">
<img width="1381" alt="Screenshot 2022-12-14 at 11 42 48" src="https://user-images.githubusercontent.com/54355787/207548044-b9e4f25b-f1d7-4d49-9ae1-81a48e5e8a91.png">

Need some help!

**Comment by breck7** [comment]
Yes @rkimera94 that is just a path issue. I have a hacky workaround on pldb.com but didn't implement it yet on this site. For now you can just do "npm run local" to get a working local version. If you'd like to move that to a separate issue, that would be helpful, thanks!
