### ISSUE TITLE
Fix path issue for local instances 

### ISSUE THREAD

**Issue by rkimera94** [breck7/CancerDB#20]
@breck 
 
<img width="615" alt="Screenshot 2023-01-04 at 20 44 37" src="https://user-images.githubusercontent.com/54355787/210617204-3f74d942-682a-4e54-9af5-08d7be57b0c8.png">

**Comment by breck7** [comment]
Just a dynamic site now so this should be fixed when doing `npm run local`

**Comment by rkimera94** [comment]
good! @breck7  let me update my local instance
