### ISSUE TITLE
404's list

### ISSUE THREAD

**Issue by stavares843** [breck7/CancerDB#21]
Status | URL | Source link text
-- | -- | --
-1 Not found: The server name or address could not be resolved | https://heal.cancerdb.com/search | [form/action(get)](https://cancerdb.com/)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/about.scroll | [View source](https://cancerdb.com/pages/about.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/lists.scroll | [View source](https://cancerdb.com/lists/lists.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/funQuiz.scroll | [View source](https://cancerdb.com/posts/funQuiz.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/sayCheese.scroll | [View source](https://cancerdb.com/posts/sayCheese.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/sponsor.scroll | [View source](https://cancerdb.com/pages/sponsor.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/natureCalls.scroll | [View source](https://cancerdb.com/posts/natureCalls.html)
404 Not Found | https://cancerdb.com/nginxDaily.html | [Traffic Today](https://cancerdb.com/)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/moonbathing.scroll | [View source](https://cancerdb.com/posts/index.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/hawaii-cancer-moonshot.scroll | [View source](https://cancerdb.com/posts/index.html)
404 Not Found | https://cancerdb.com/nginxDailyAll.html | [Traffic Trends](https://cancerdb.com/)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/cat-food.scroll | [View source](https://cancerdb.com/posts/cat-food.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/prostateExams.scroll | [View source](https://cancerdb.com/posts/prostateExams.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/treatments.scroll | [View source](https://cancerdb.com/lists/treatments.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/david-fund.scroll | [View source](https://cancerdb.com/posts/index.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/holey-moley.scroll | [View source](https://cancerdb.com/posts/index.html)
404 Not Found | https://github.com/breck7/CancerDB/blob/main/site/commonCancerTypes.scroll | [View source](https://cancerdb.com/lists/commonCancerTypes.html)

**Comment by breck7** [comment]
Most should be fixed.
