### ISSUE TITLE
Searching a item returns error

### ISSUE THREAD

**Issue by stavares843** [breck7/CancerDB#22]
STR:
- go to https://cancerdb.com/
- search anything
- returns error

<img width="1050" alt="Captura de ecrã 2023-02-10, às 17 52 25" src="https://user-images.githubusercontent.com/29093946/218161558-2f20c68f-41b4-4680-9c8f-7af907a47548.png">

**Comment by breck7** [comment]
Things are starting to live now. Should be >15,000 lines of data to search across by Friday.
