### ISSUE TITLE
Add all cancer registries worldwide

### ISSUE THREAD

**Issue by breck7** [breck7/CancerDB#23]
According to https://www.iccp-portal.org/cancer-registries 

"Worldwide, there are more than 700 cancer registries."

We currently only have 1: https://cancerdb.com/search.html?q=select+type%0D%0Awhere+type+includes+tumorRegistry

**Comment by ghost** [comment]
The following search query gave me results:
https://cancerdb.com/search.html?q=select+type%0D%0Awhere+type+includes+registry

I will try adding , if i am allowed to.

**Comment by ghost** [comment]
@breck7 : There are over 150 countries and the source cited says there are over 700 registries world wide.
Approximate average of 4 cancer registries per country should be provided.

There seems to be no ready made list. Sourcing it will take time, should i continue ?

**Comment by breck7** [comment]
@SRS-WRKS I would *not* recommend doing this one by hand. I will be calling some people to see if we can import someone else's list! Sorry I should start adding more details to these issues.

**Comment by ghost** [comment]
@breck7 : I have already done some groundwork. Can i contribute as much as i am able, manually ?

Your team of people can do all the hifi stuff.

**Comment by breck7** [comment]
Of course @SRS-WRKS ! I still believe nothing beats human expertise!

**Comment by breck7** [comment]
closing for now
