### ISSUE TITLE
cancerDB has no tests

### ISSUE THREAD

**Issue by ghost** [breck7/CancerDB#28]
The lack of tests in cancerDB seems to make contribution to CancerDB difficult.

Are there plans to include tests, are contributions welcome ?

**Comment by breck7** [comment]
Sorry that there are not enough tests, but there are a number of tests in `./code/test.js` that you can run with `npm test`. Are they not working for you?

**Comment by ghost** [comment]
Mighty  @breck7 
Does something really exist if it is not mentioned in readme.scroll.

I shall update the readme.scroll for benefit of future generations :)
