### ISSUE TITLE
Dynamic Site path routing for About tab.

### ISSUE THREAD

**Issue by rkimera94** [breck7/CancerDB#31]
@breck7  Hi, good work! most of the site tabs are now good. Only experiencing it for the  /pages/about.html
<img width="1281" alt="Screenshot 2023-03-06 at 18 53 37" src="https://user-images.githubusercontent.com/54355787/223161938-875b72a9-f155-46fc-ab95-8783e0ad55b4.png">
Reference Issue
https://github.com/breck7/CancerDB/issues/20

**Comment by breck7** [comment]
Hi @rkimera94 ! That looks like a very old site. Can you try?

```
git pull
npm install .
npm run build
npm run local
```

I'll close this for now, but please reopen if you still get that.
