### ISSUE TITLE
stale files created from files in truebase/things folder not being cleared in deployment directory 

### ISSUE THREAD

**Issue by ghost** [breck7/CancerDB#35]
There seems to be no documented way to clean files that were created by cdb  that were added by mistake but  were successfully compiled into the deployment directory.

Deploying from a directory already containing a previous successfully compiled checkout could lead to confusion.

**Comment by breck7** [comment]
Okay so the new version of TrueBase no longer has a build step. Everything is generated and served from in memory. I think this should get rid of this issue?

I'll close, but feel free to reopen if it still happens.

Thanks @SRS-WRKS !

**Comment by ghost** [comment]
@breck7 : Even latex has a build step and that allows people to include one file in another , very reliably.

Having a build step has its advantages, especially for issues like ( https://github.com/breck7/jtree/issues/118 )

Allowing people to use a build script could be useful and make things more flexible.
