### ISSUE TITLE
reference keys value underscore  interpration issues

### ISSUE THREAD

**Issue by ghost** [breck7/CancerDB#39]
the value of key reference seems to have an issue interpreting its values.

The value for key reference value containing URL https://extranet.who.int/ncdccs/Data/ALB_B5_NCCP%20Albania%20English.pdf is interpreted on the cancer DB web portal  as https://extranet.who.int/ncdccs/Data/ALB%3C/em%3EB5_NCCP%20Albania%20English.pdf

The value for key reference containing URL https://www.iccp-portal.org/system/files/plans/ALB_2020.pdf  is interpreted on the cancer DB portal as https://www.iccp-portal.org/system/files/plans/ALB%3Cem%3E2020.pdf

The issue seems to be interpretation of  underscore in the value, if it is part of some sub-string of the reference keys value for some reason.

**Comment by breck7** [comment]
Ah yes, those are triggering scroll to interpret them as underscores for emphasis. We hit this in PLDB too. I forget what the best workaround was.

**Comment by ghost** [comment]
Found the issue, that seems to be about underscores inside quotes. These are http urls with no quotes.
https://github.com/breck7/pldb/issues/340#issuecomment-1326861892
