### ISSUE TITLE
What is JTree?

### ISSUE THREAD

**Issue by adamredwoods** [breck7/CancerDB#6]
Interesting project, it took me a while to understand what this is attempting to be.

I also noted that this uses JTree notation, which wasn't obvious at first, and could use better docs: https://github.com/breck7/jtree
Scroll gave more insight: https://github.com/breck7/scroll

For example, how specifically is grammar supported here? I would personally think more in graph terms, node, edge, relation, etc.

I have my own personal knowledge notes for cancer, and I have been thinking about a markdown-as-graph-db tool as well (Aspen/Obsidian).

**Comment by breck7** [comment]
> For example, how specifically is grammar supported here? I would personally think more in graph terms, node, edge, relation, etc.

Great question! Grammar needs better docs. High on my todo list. I can address your questions related to graphs as well.

> I have my own personal knowledge notes for cancer, and I have been thinking about a markdown-as-graph-db tool as well (Aspen/Obsidian).

Very cool! Do you have a link to the repo?

Have you seen PLDB.com? https://pldb.com/ That's not only a fun project in its own right, but serving as a training ground for this project.
